ALTER TABLE "CompanyLocation"
ADD COLUMN "openTime" TEXT NOT NULL DEFAULT '09:00',
ADD COLUMN "closeTime" TEXT NOT NULL DEFAULT '21:00',
ADD COLUMN "workingDays" INTEGER[] NOT NULL DEFAULT ARRAY[0,1,2,3,4,5,6];
